/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import dataacces.DataAccess;
import dto.Reseña;
import java.awt.Event;
import java.awt.Frame;
import javax.swing.JPanel;

/**
 *
 * @author Miquel
 */
public class AddReseñaDialog extends javax.swing.JDialog {

    private pnlVer padre;
    private Main padremain;
    private DataAccess data = new DataAccess();

    public AddReseñaDialog() {
    }

    /**
     * Creates new form AddReseñaDialog
     */
    public AddReseñaDialog(Frame parentmain, boolean modal, JPanel padre) {
        super(parentmain, modal);
        this.padremain = (Main) parentmain;
        this.padre = (pnlVer) padre;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddReseña = new javax.swing.JLabel();
        lblAddDesc = new javax.swing.JLabel();
        spnValoracion = new javax.swing.JSpinner();
        lblAddValoracion = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        lblAddReseña.setText("Añadir Reseña...");
        getContentPane().add(lblAddReseña);
        lblAddReseña.setBounds(35, 38, 110, 16);

        lblAddDesc.setText("Descripcion:");
        getContentPane().add(lblAddDesc);
        lblAddDesc.setBounds(50, 130, 70, 16);

        spnValoracion.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        getContentPane().add(spnValoracion);
        spnValoracion.setBounds(130, 80, 64, 22);

        lblAddValoracion.setText("Valoracion:");
        getContentPane().add(lblAddValoracion);
        lblAddValoracion.setBounds(60, 80, 70, 16);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(390, 270, 72, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(270, 270, 110, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 130, 340, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
        padre.remove(this);
        padre.repaint();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        if (!jTextArea1.getText().isEmpty()) {
            Reseña addReseña = new Reseña();
            addReseña.setDescripcion(jTextArea1.getText());
            addReseña.setValoracion((int) spnValoracion.getValue());
            addReseña.setId_usuario(padremain.getUserLogged().getId());
            addReseña.setId_establecimiento(padre.getPadre().getLstEstablecimientos().getSelectedValue().getId());

            if (data.insertReseña(addReseña) > 0) {
                this.setVisible(false);
                padre.setVisible(true);
                padre.remove(this);
                padre.remove(padre.getLstReseña());
                padre.rellenarReseñas();
                padre.rellenarDatos();
                padre.repaint();
            }
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAddDesc;
    private javax.swing.JLabel lblAddReseña;
    private javax.swing.JLabel lblAddValoracion;
    private javax.swing.JSpinner spnValoracion;
    // End of variables declaration//GEN-END:variables
}
