/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dataacces.DataAccess;
import dto.ContactInfo;
import dto.Establecimiento;
import dto.Reseña;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;

/**
 *
 * @author Miquel
 */
public class pnlVer extends javax.swing.JPanel {

    private PnlLoged padre;
    private DataAccess data = new DataAccess();
    private Establecimiento verEstablecimiento;

    /**
     * Creates new form AnadirAlojamiento
     */
    public pnlVer(PnlLoged padre) {
        this.padre = padre;
        this.verEstablecimiento = padre.getLstEstablecimientos().getSelectedValue();
        initComponents();
        lstReseña = new javax.swing.JList<>();
        srcReseña = new javax.swing.JScrollPane();
        rellenarReseñas();

        //Salto de linea en txtArea
        txtDescripcion.setWrapStyleWord(true);
        txtDescripcion.setLineWrap(true);

        //Deshabilitar los inputs
        txtNombre.setEditable(false);
        txtDireccion1.setEditable(false);
        txtDescripcion.setEditable(false);
        txtPais1.setEditable(false);
        txtEstado.setEditable(false);
        sldValoración.setEnabled(false);
        btnEditReseña.setEnabled(false);
        btnEditReseña.setVisible(false);

        //Rellenar datos del Alojamiento seleccionado
        rellenarDatos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInputError = new javax.swing.JLabel();
        lblEditValoracio = new javax.swing.JLabel();
        lblEditDescripcion = new javax.swing.JLabel();
        lblEditEstado = new javax.swing.JLabel();
        lblEditNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtEstado = new javax.swing.JTextField();
        btnAddReseña = new javax.swing.JButton();
        lblVerEstablecimiento = new javax.swing.JLabel();
        sldValoración = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEditDirección1 = new javax.swing.JLabel();
        txtDireccion1 = new javax.swing.JTextField();
        lblEditPais1 = new javax.swing.JLabel();
        txtPais1 = new javax.swing.JTextField();
        btnVolver1 = new javax.swing.JButton();
        btnEditReseña = new javax.swing.JButton();

        setLayout(null);

        lblInputError.setForeground(new java.awt.Color(255, 0, 0));
        add(lblInputError);
        lblInputError.setBounds(310, 60, 260, 20);

        lblEditValoracio.setText("Valoración:");
        add(lblEditValoracio);
        lblEditValoracio.setBounds(230, 330, 70, 16);

        lblEditDescripcion.setText("Descripción:");
        add(lblEditDescripcion);
        lblEditDescripcion.setBounds(240, 130, 90, 16);

        lblEditEstado.setText("Estado:");
        add(lblEditEstado);
        lblEditEstado.setBounds(260, 300, 50, 20);

        lblEditNombre.setText("Nombre:");
        add(lblEditNombre);
        lblEditNombre.setBounds(250, 90, 50, 16);
        add(txtNombre);
        txtNombre.setBounds(310, 90, 330, 22);

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        add(jScrollPane1);
        jScrollPane1.setBounds(310, 130, 330, 86);
        add(txtEstado);
        txtEstado.setBounds(310, 300, 330, 22);

        btnAddReseña.setText("Añadir Reseña");
        btnAddReseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddReseñaActionPerformed(evt);
            }
        });
        add(btnAddReseña);
        btnAddReseña.setBounds(620, 510, 130, 23);

        lblVerEstablecimiento.setText("Ver Establecimiento");
        add(lblVerEstablecimiento);
        lblVerEstablecimiento.setBounds(50, 80, 190, 16);

        sldValoración.setMaximum(5);
        sldValoración.setValue(1);
        add(sldValoración);
        sldValoración.setBounds(320, 330, 160, 20);

        jLabel1.setText("0");
        add(jLabel1);
        jLabel1.setBounds(310, 330, 10, 16);

        jLabel2.setText("5");
        add(jLabel2);
        jLabel2.setBounds(480, 330, 10, 16);

        lblEditDirección1.setText("Dirección:");
        add(lblEditDirección1);
        lblEditDirección1.setBounds(250, 230, 60, 16);
        add(txtDireccion1);
        txtDireccion1.setBounds(310, 230, 330, 22);

        lblEditPais1.setText("Pais:");
        add(lblEditPais1);
        lblEditPais1.setBounds(280, 260, 30, 16);
        add(txtPais1);
        txtPais1.setBounds(310, 260, 330, 22);

        btnVolver1.setText("Volver");
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });
        add(btnVolver1);
        btnVolver1.setBounds(50, 510, 90, 23);

        btnEditReseña.setText("Editar Reseña");
        add(btnEditReseña);
        btnEditReseña.setBounds(495, 510, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddReseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddReseñaActionPerformed
        // TODO add your handling code here:
        AddReseñaDialog addReseñaDialog = new AddReseñaDialog(this.padre.getPadre(), true, this);
        addReseñaDialog.setVisible(true);
    }//GEN-LAST:event_btnAddReseñaActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        padre.setVisible(true);
        padre.remove(this);
        padre.repaint();
    }//GEN-LAST:event_btnVolver1ActionPerformed

    //Funcion que rellena los datos del alojamiento seleccionado.
    public void rellenarDatos() {
        txtNombre.setText(verEstablecimiento.getNombre());
        txtDescripcion.setText(verEstablecimiento.getDescripcion());

        ContactInfo info = data.getInfoContact(verEstablecimiento);
        txtDireccion1.setText(info.getDireccion());
        txtPais1.setText(info.getPais());

        if (info.isEstado()) {
            txtEstado.setText("Abierto");
        } else {
            txtEstado.setText("Cerrado");
        }

        //Cargamos la valoración
        int valoración = Math.round(data.getValoracioEstablecimientoAvg(verEstablecimiento.getId()));
        sldValoración.setValue(valoración);
    }

    public void rellenarReseñas() {

        //Cargamos los alojamientos
        this.add(srcReseña);
        ArrayList<Reseña> reseñas = data.getEstabReseñas(verEstablecimiento);
        DefaultListModel<Reseña> dflmo = new DefaultListModel<>();
        for (Reseña reseña : reseñas) {
            dflmo.addElement(reseña);
        }
        
        lstReseña.setModel(dflmo);
        srcReseña.setViewportView(lstReseña);
        srcReseña.setBounds(230, 360, 430, 146);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddReseña;
    private javax.swing.JButton btnEditReseña;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEditDescripcion;
    private javax.swing.JLabel lblEditDirección1;
    private javax.swing.JLabel lblEditEstado;
    private javax.swing.JLabel lblEditNombre;
    private javax.swing.JLabel lblEditPais1;
    private javax.swing.JLabel lblEditValoracio;
    private javax.swing.JLabel lblInputError;
    private javax.swing.JLabel lblVerEstablecimiento;
    private javax.swing.JSlider sldValoración;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPais1;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JScrollPane srcReseña;
    private javax.swing.JList<Reseña> lstReseña;

    public JList<Reseña> getLstReseña() {
        return lstReseña;
    }

    public PnlLoged getPadre() {
        return padre;
    }

    

}
