/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import dataacces.DataAccess;
import dto.Usuario;
import java.util.Arrays;
import java.util.Objects;

/**
 *
 * @author Miquel
 */
public class RegisterDialog extends javax.swing.JDialog {

    private Main pantallaPricipal;

    /**
     * Creates new form LoginDialog
     */
    public RegisterDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        pantallaPricipal = (Main) parent;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIntro = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);
        getContentPane().setLayout(null);

        lblIntro.setText("Introduce sus credenciales:");
        getContentPane().add(lblIntro);
        lblIntro.setBounds(30, 20, 160, 20);

        lblPassword.setText("Password:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(90, 110, 70, 16);

        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(110, 60, 50, 16);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(170, 60, 140, 22);

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(220, 150, 90, 23);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(170, 110, 140, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Comprobamos si existe el usuario y lo seteamos como usuario logeado.
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //Recoger datos de los campos.
        String emailValue = txtEmail.getText().trim().toLowerCase();
        String valuePassword = String.valueOf(txtPassword.getPassword()).trim();
        

        //Validamos los datos introducidos antes de enviarlos a la base de datos.
        if (!emailValue.isBlank() && !valuePassword.isBlank()) {
            //Comprobamos si existe el usuario en la base de datos.
            DataAccess data = new DataAccess();
            Usuario dbUsuario = data.getUser(emailValue);
            if (dbUsuario.getEmail()== null) {
                System.out.println("Entra");
                Usuario newUsuario = new Usuario();
                newUsuario.setEmail(emailValue);
                newUsuario.setPassword(valuePassword);
                
                if(data.insertUsuario(newUsuario) > 0){
                    this.setVisible(false);
                    pantallaPricipal.isLogedIn(false);
                }
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIntro;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
