/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import dataacces.DataAccess;
import dto.Allotjament;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author Miquel
 */
public class PnlLoged extends javax.swing.JPanel {

    private Main padre;
    private DataAccess data = new DataAccess();

    /**
     * Creates new form PnlLoged
     */
    public PnlLoged(Main padre) {
        this.padre = padre;
        initComponents();
        loadUserComponents();
    }
    
    //para recoger el JFrame desde los hijos de esta clase.
    public Main getPadre() {
        return padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddAlojamiento = new javax.swing.JButton();

        setLayout(null);

        btnAddAlojamiento.setText("Añadir \nAlojamiento");
        btnAddAlojamiento.setToolTipText("");
        btnAddAlojamiento.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAlojamientoActionPerformed(evt);
            }
        });
        add(btnAddAlojamiento);
        btnAddAlojamiento.setBounds(510, 50, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    //Una vez instanciados los componentes estaticos, instanciamos los componentes de usuario.
    private void loadUserComponents() {
        lstAlojamientos = new javax.swing.JList<>();
        scrAlojamientos = new javax.swing.JScrollPane();
        btnMostrarDetalles = new javax.swing.JButton();
        
        //Cargamos los alojamientos
        this.add(scrAlojamientos);
        scrAlojamientos.setBounds(80, 120, 560, 200);
        cargarAlojamientos();
        lstAlojamientos.addListSelectionListener((javax.swing.event.ListSelectionEvent evt) -> {
            lstAlojamientosValueChanged(evt);
        });
        
        
        btnMostrarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDetallesActionPerformed(evt);
            }
        });
    }

    //Funcion que carga los Alojamientos dentro de la lista.
    public void cargarAlojamientos() {
        ArrayList<Allotjament> alojamientos = data.getAllotjaments(padre.getUserLogged().getId());
        DefaultListModel<Allotjament> dflmo = new DefaultListModel<>();
        for (Allotjament alojamiento : alojamientos) {
            dflmo.addElement(alojamiento);
        }

        lstAlojamientos.setModel(dflmo);
        scrAlojamientos.setViewportView(lstAlojamientos);
    }

    //Evento que se activa cada vez que se cambia el alojamiento seleccionado.
    private void lstAlojamientosValueChanged(javax.swing.event.ListSelectionEvent evt) {
        
        //Metodo para anular la doble entrada al cambiar el valor de la lista de alojamientos.
        if (!evt.getValueIsAdjusting()) {
            if (lstAlojamientos.getSelectedValue() != null) {
                Allotjament detallesAllotjament = data.getAllotjament(lstAlojamientos.getSelectedValue().getId());
                this.add(btnMostrarDetalles);
                btnMostrarDetalles.setBounds(80, 340, 560, 50);
                btnMostrarDetalles.setText("Ver/Editar");
                this.repaint();

            } else {
                this.remove(btnMostrarDetalles);
                this.repaint();
            }
        }
    }
    private void btnAddAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAlojamientoActionPerformed
        // TODO add your handling code here:
        pnlAddAlojamiento = new pnlAnadirAlojamiento(this);
        padre.add(pnlAddAlojamiento);
        pnlAddAlojamiento.setBounds(0, 0, 800, 540);
        pnlAddAlojamiento.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddAlojamientoActionPerformed
    private void btnMostrarDetallesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        pnlVerModificar = new pnlVerModificar(this);
        padre.add(pnlVerModificar);
        pnlVerModificar.setBounds(0, 0, 800, 540);
        pnlVerModificar.setVisible(true);
        this.setVisible(false);
    }

    public JList<Allotjament> getLstAlojamientos() {
        return lstAlojamientos;
    }

    private javax.swing.JScrollPane scrAlojamientos;
    private javax.swing.JList<Allotjament> lstAlojamientos;
    private javax.swing.JPanel pnlAddAlojamiento;
    private javax.swing.JPanel pnlVerModificar;
    private javax.swing.JButton btnMostrarDetalles;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAlojamiento;
    // End of variables declaration//GEN-END:variables
}
