package spdvid.evtmallorca;

import spdvid.evtmallorca.dialogs.LoginDialog;
import spdvid.evtmallorca.dto.Allotjament;
import spdvid.evtmallorca.panels.PanelDetallAllotjament;
import spdvid.evtmallorca.panels.PanelInsertAllotjament;
import spdvid.evtmallorca.panels.PanelLlistaAllojtaments;
import spdvid.garciajodar_tarea1.dto.Usuari;

/**
 *
 * @author Miguel
 */
public class Main extends javax.swing.JFrame {

    private Usuari authenticatedUser = null;
    private PanelLlistaAllojtaments pnlAllojtaments = null;
    private PanelDetallAllotjament pnlDetallAllotjament = null;
    private PanelInsertAllotjament pnlInsertAllotjament = null;
    
    /**
     * Creates new form Main
     */
    public Main() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnShowLoginDialog = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcomeMessage = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlHeader.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblTitle.setText("EVT MALLORCA");
        pnlHeader.add(lblTitle);
        lblTitle.setBounds(10, 10, 500, 80);

        btnShowLoginDialog.setText("Login");
        btnShowLoginDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowLoginDialogActionPerformed(evt);
            }
        });
        pnlHeader.add(btnShowLoginDialog);
        btnShowLoginDialog.setBounds(600, 50, 72, 23);

        btnLogout.setText("Sign out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlHeader.add(btnLogout);
        btnLogout.setBounds(690, 50, 74, 23);

        lblWelcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcomeMessage.setText("Welome username");
        lblWelcomeMessage.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pnlHeader.add(lblWelcomeMessage);
        lblWelcomeMessage.setBounds(600, 30, 160, 16);

        getContentPane().add(pnlHeader);
        pnlHeader.setBounds(10, 10, 780, 100);

        pnlMain.setMinimumSize(new java.awt.Dimension(780, 700));
        pnlMain.setPreferredSize(new java.awt.Dimension(780, 700));
        pnlMain.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N
        pnlMain.add(lblLogo);
        lblLogo.setBounds(180, 30, 410, 420);

        getContentPane().add(pnlMain);
        pnlMain.setBounds(10, 100, 780, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void btnShowLoginDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowLoginDialogActionPerformed
        LoginDialog loginDialog = new LoginDialog(this, true);
        loginDialog.setVisible(true);
        if (authenticatedUser != null) {
            btnShowLoginDialog.setEnabled(false);
            btnLogout.setEnabled(true);
            lblWelcomeMessage.setText("Welcome " + authenticatedUser.getNom());
            lblWelcomeMessage.setVisible(true);
            pnlAllojtaments = new PanelLlistaAllojtaments(authenticatedUser.getId(), this);
            pnlMain.removeAll();
            pnlMain.add(pnlAllojtaments);
            pnlMain.repaint();
        }
    }//GEN-LAST:event_btnShowLoginDialogActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        authenticatedUser = null;
        btnShowLoginDialog.setEnabled(true);
        btnLogout.setEnabled(false);
        lblWelcomeMessage.setText("Nobody is logged in.");
        lblWelcomeMessage.setVisible(false);
        pnlMain.removeAll();
        pnlMain.add(lblLogo);
        pnlMain.repaint();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        btnLogout.setEnabled(false);
        //btnLogout.setVisible(false);
        lblWelcomeMessage.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    public void userLoggedIn(Usuari user) {
        authenticatedUser = user;
    }

    public void showPnlDetallAllotjament(Allotjament allotjament) {
        pnlDetallAllotjament = new PanelDetallAllotjament(allotjament, this);
        pnlMain.removeAll();
        pnlMain.add(pnlDetallAllotjament);
        pnlMain.repaint();
    }
    
    public void showPnlLlistaAllotjaments() {
        pnlMain.removeAll();
        pnlMain.add(pnlAllojtaments);
        pnlMain.repaint();
    }
    
    public void showPnlInsertAllotjament() {
        pnlMain.removeAll();
        pnlInsertAllotjament = new PanelInsertAllotjament(this);
        pnlMain.add(pnlInsertAllotjament);
        pnlMain.repaint();
    }
    
    public Usuari getAuthenticatedUser() {
        return authenticatedUser;
    }
    
    public void reloadPnlLlistaAllotjaments() {
        pnlMain.removeAll();
        pnlAllojtaments = new PanelLlistaAllojtaments(authenticatedUser.getId(), this);
        pnlMain.add(pnlAllojtaments);
        pnlMain.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnShowLoginDialog;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
