package spdvid.evtmallorca.panels;

import spdvid.evtmallorca.Main;
import spdvid.evtmallorca.dataaccess.DataAccess;
import spdvid.evtmallorca.dto.Allotjament;
import spdvid.evtmallorca.tablemodels.AllotjamentTableModel;

/**
 *
 * @author Miguel
 */
public class PanelLlistaAllojtaments extends javax.swing.JPanel {
    private DataAccess da = new DataAccess();
    private Main mainJFrame = null;
    
    /**
     * Creates new form pnlAllojtaments
     */
    public PanelLlistaAllojtaments(int userId, Main mainJFrame) {
        initComponents();
        this.mainJFrame = mainJFrame;
        setSize(780, 490);
        tblAllotjaments.setModel(new AllotjamentTableModel((da.getAllotjaments(userId))));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblAllotjaments = new javax.swing.JTable();
        btnShowInsertPanel = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(780, 490));
        setLayout(null);

        tblAllotjaments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAllotjaments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAllotjamentsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAllotjaments);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 590, 402);

        btnShowInsertPanel.setText("New...");
        btnShowInsertPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInsertPanelActionPerformed(evt);
            }
        });
        add(btnShowInsertPanel);
        btnShowInsertPanel.setBounds(495, 420, 90, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void tblAllotjamentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAllotjamentsMouseClicked
        AllotjamentTableModel atbm = (AllotjamentTableModel) tblAllotjaments.getModel();
        int selectedRowIndex = tblAllotjaments.getSelectedRow();
        //atbm.getValueAt(selectedRowIndex, 0);
        Allotjament selectedAllotjament = atbm.getValueAtRow(selectedRowIndex);
        System.out.print("selected allotjament id: " + selectedAllotjament.getId());
        //System.out.print(((Main)this.getRootPane().getContentPane()));
//        ((Main)this.getRootPane().getContentPane()).showPnlDetallAllotjament(selectedAllotjament);
        mainJFrame.showPnlDetallAllotjament(selectedAllotjament);
    }//GEN-LAST:event_tblAllotjamentsMouseClicked

    private void btnShowInsertPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInsertPanelActionPerformed
        mainJFrame.showPnlInsertAllotjament();
    }//GEN-LAST:event_btnShowInsertPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowInsertPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAllotjaments;
    // End of variables declaration//GEN-END:variables
}
