package prova;

import dataacces.DataAccess;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.beans.JavaBean;
import java.util.ArrayList;
import javax.swing.Timer;
import jpanelimagen.JPanelImagen;

public class Main extends javax.swing.JFrame {

    private DataAccess data = new DataAccess();

    Integer ParentHeight;
    Integer ParentWidth;

    public Main() {
        initComponents();
        ParentHeight = 650;
        ParentWidth = 790;
        setSize(ParentWidth, ParentHeight);
        setLocation(0, 0);

        panelimagen = new JPanelImagen(data.getImagesAllotjament(1), 3000, ParentHeight, ParentWidth);
        panelimagen.setBounds(0, 0, jPanel2.getWidth(), jPanel2.getHeight());
        jPanel2.add(panelimagen, BorderLayout.CENTER);
        lblInfo.setText(panelimagen.getFullInfo());

        this.pack();
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 550));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 800, 450);

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext);
        btnNext.setBounds(710, 480, 72, 23);

        btnPrev.setText("Prev");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrev);
        btnPrev.setBounds(620, 480, 80, 23);

        jCheckBox1.setText("Auto");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(530, 480, 85, 20);
        getContentPane().add(lblInfo);
        lblInfo.setBounds(30, 470, 420, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

        jPanel2.setBounds(0, 0, this.getWidth(), this.getHeight() - 100);
        jPanel2.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        panelimagen.nextImage();
        String fullInfo = panelimagen.getFullInfo();
        lblInfo.setText(fullInfo);


    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed

        panelimagen.previousImage();
        String fullInfo = panelimagen.getFullInfo();
        lblInfo.setText(fullInfo);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrevActionPerformed

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged

        if (jCheckBox1.isSelected()) {
            panelimagen.autoSlider();

            setFileName();

        } else {

            panelimagen.stopSlider();
            setFileName();

        }


    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    public void setFileName() {

        Timer changeImage = null;
        changeImage = new Timer(3000, (ActionEvent e1) -> {
            String fileInfo = panelimagen.getFullInfo();
            lblInfo.setText(fileInfo);

        });
        changeImage.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblInfo;
    // End of variables declaration//GEN-END:variables
    private jpanelimagen.JPanelImagen panelimagen;

}
